[package]
name = "multiply_accumulator_by_constant_6502"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.9"
rand = "0.8.5"

[dependencies.strop]
path = "../../"
