name: z80

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --features z80 --no-default-features
    - name: Test
      run: cargo test --features z80 --no-default-features --lib
    - name: Lint
      run: cargo clippy --features z80 --no-default-features -- -Dwarnings
